server:
  port: 9001

spring:
  application:
    name: video-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud_video?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 47.104.241.237:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8720
#      config:
#        server-addr: 47.104.241.237:8848
#        file-extension: yml
#        group: DEFAULT_GROUP



# 控制台输出sql、下划线转驼峰
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

customization:
  testVal: 1